# Generated by Django 5.1.6 on 2025-02-18 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_category_product_vendor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name_plural': 'Product Categories'},
        ),
    ]
